startLesson1: 
	cd cmd/compositeLiteral && go run main.go

startLesson2:
	cd cmd/dataStructures && go run main.go

startLesson3:
	cd cmd/functions/cmd && go run main.go

startLesson4:
	cd cmd/concurrency/cmd && go run main.go

startLesson5:
	cd cmd/channels/cmd && go run main.go